[book]
authors = ["Andrey Fedoseev"]
language = "en"
multilingual = false
src = "src"
title = "DOSBox Pure - Configuration and Usage Guide"

[preprocessor.alerts]

[output.html]
additional-css = ["custom.css"]
