[book]
authors = ["Andrey Fedoseev"]
language = "en"
multilingual = false
src = "src"
title = "DOSBox Pure - Configuration and Usage Guide"

[preprocessor.alerts]

[output.html]
additional-css = ["custom.css"]
git-repository-url = "https://github.com/adfxyz/dosbox-pure-guide/tree/main/en/"
edit-url-template = "https://github.com/adfxyz/dosbox-pure-guide/tree/main/en/{path}"