[book]
authors = ["Andrey Fedoseev"]
language = "ru"
multilingual = false
src = "src"
title = "DOSBox Pure - Руководство по настройке и использованию"

[preprocessor.alerts]

## Keyboard Layout

[output.html]
additional-css = ["custom.css"]
