[book]
authors = ["Andrey Fedoseev"]
language = "ru"
multilingual = false
src = "src"
title = "DOSBox Pure - Руководство по настройке и использованию"

[preprocessor.alerts]

[output.html]
additional-css = ["custom.css"]
git-repository-url = "https://github.com/adfxyz/dosbox-pure-guide/tree/main/ru/"
edit-url-template = "https://github.com/adfxyz/dosbox-pure-guide/tree/main/ru/{path}"